apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: nginx-test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/apps"