apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
  namespace: nginx-test
spec:
  selector:
    matchLabels:
      app: nginx-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx
          subPath: nginx.conf
        - mountPath: /usr/share/nginx/html
          name: task-pv-storage
      volumes:
      - name: nginx
        configMap:
          name: nginx-config
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
---
apiVersion: v1
kind: Service
metadata: 
    name: nginx-pod
    namespace: nginx-test
    labels:
        app: nginx-pod
spec:
    type: NodePort
    selector:
        app: nginx-pod
    ports:
    - port: 8888
      nodePort: 31033