apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-map
  namespace: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-config-map
  template:
    metadata:
      labels:
        app: nginx-config-map
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx
          subPath: nginx.conf
      volumes:
      - name: nginx
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata: 
    name: nginx-config-map
    namespace: nginx-test
    labels:
        app: nginx-config-map
spec:
    type: NodePort
    selector:
        app: nginx-config-map
    ports:
    - port: 8888
      nodePort: 31032